name: spark-env
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - findspark
    - pip
    - pip: 
        - pyspark